### ISSUE TITLE
More dev friendly errors

### ISSUE THREAD

**Issue by vikiival** [kodadot/uniquery#21]
It would be nicer to throw away errors that are more user friendly

This one could be "unable to perform fetch for non-existing indexer, add parameter prefix when calling getClient"

![image](https://user-images.githubusercontent.com/22471030/226045964-210f1246-c208-46f0-bfa2-866cc84faeff.png)

ht/ @poppyseedDev

**Comment by roiLeo** [comment]
`Indexer not found` when no client set, shoudl fallback to smething default

**Comment by vikiival** [comment]
> shoudl fallback to smething default

and It would return undefined if you provide bad params.

We can either implement:
- #16 
or 
- log warn wen client is not supplied

**Comment by roiLeo** [comment]
or add it to readme (or jsdoc) so devs won't loose time debuging this one

**Comment by vikiival** [comment]
> or add it to readme (or jsdoc) so devs won't loose time debuging this one

added [1764cf0](https://github.com/kodadot/uniquery/commit/1764cf0f10472d4d65cdb8a98641d34272a1849d)
