### ISSUE TITLE
`client.getCollectionStatsById`

### ISSUE THREAD

**Issue by roiLeo** [kodadot/uniquery#41]
implement Collection Stats

**Comment by roiLeo** [comment]
something wrong with types?

<img width="596" alt="Capture d’écran 2023-12-29 à 11 44 43 AM" src="https://github.com/kodadot/uniquery/assets/9987732/ccf31b7c-4bce-4fe1-bf07-46cae2e3d0d1">

**Comment by vikiival** [comment]
It has old types afaik

**Comment by roiLeo** [comment]
outdated, only issue with types
